### ISSUE TITLE
 Configuration property "local-dns-names" is not defined

### ISSUE THREAD

**Issue by sashasaturn** [davehorton/drachtio-siprec-recording-client#1]
Error: Configuration property "local-dns-names" is not defined
    at Config.get (/app/node_modules/config/lib/config.js:203:11)
    at Object.srf.use [as handle] (/app/app.js:39:23)
    at next (/app/node_modules/drachtio-srf/lib/proto.js:200:15)
    at Object.handle (/app/node_modules/drachtio-srf/lib/srf.js:113:7)
    at next (/app/node_modules/drachtio-srf/lib/proto.js:200:15)
    at Function.app.handle (/app/node_modules/drachtio-srf/lib/proto.js:209:3)
    at DrachtioAgent.app [as puntUpTheMiddleware] (/app/node_modules/drachtio-srf/lib/connect.js:17:9)
    at DrachtioAgent._onMsg (/app/node_modules/drachtio-srf/lib/drachtio-agent.js:595:18)
    at emitTwo (events.js:126:13)
    at WireProtocol.emit (events.js:214:7)

**Comment by sashasaturn** [comment]
I figured that out ... in /config/default.json.example variable is called local-dns-name meanwhile code is basically trying to find local-dns-names

**Comment by davehorton** [comment]
ok thanks.  I've not spent that much time on this project, so let me know if you hit any other issues and I will try to clean them up

**Comment by davehorton** [comment]
If you are going to use this, could you update to the latest commit, as I checked in some updates and fixed at least one other bug you would probably encounter
